#!/bin/sh

regex='@company\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo Your $email statisfies git policy
    exit 0
else
    echo Your $email does not statisfies git policy
    exit 1
fi